### PR TITLE
Add shadow to make white video play button always visible

### PR DESCRIPTION
**Pull request by Aivean**
I changed the icon, added shadow.

New look:
image
image

Old version (outdated):
<details>
Before:
image

After:
image
<details>

### CODE REVIEW

**Review by 4vanger — DISMISSED** [review]
Ok, but this is looking like "seen" state to me. People may be skipping comments with just new videos because they will look like  comments that were watched already

**Comment by pazoozoo42** [comment]
I would rather change the `../Assets/play.svg` icon to be non-white and also change it's opacity to 1 (it's .8 now)

**Comment by Aivean** [comment]
I changed the icon, added shadow.

New look:
image
image

**Comment by SubPixelPerfect** [comment]
имхо можно тень понежнее, в 2 раза больше прозрачности

**Comment by ArtCraft** [comment]
тень слишком жёсткая, плиз добавь тени в 2 раза больше прозрачности

**Comment by Aivean** [comment]
@ArtCraft , what about now?
image

**Review by ArtCraft — APPROVED** [review]

**Pull request merged**
