### PR TITLE
ui-comments-improvements-for-light-theme

### PR DESCRIPTION
**Pull request by 3buchet**
UI improvements for comments in the light theme.

### CODE REVIEW

**Comment by Aivean** [comment]
Please include the before/after screenshots for both light and dark themes.

**Comment by 3buchet** [comment]
Hi @Aivean ,
thanks for your quick response. Please find requested screenshots:

**Before:**
light_before
**After:**
light_after

**Before:**
dark_before
**After:**
dark_after

Kind regards

**Comment by ArtCraft** [comment]
make sure that username and comment(and post) date/arrow link text have the same font size
also notice that the signature component is used in multiple places like user profiles, and search results, please make sure that new font size/color do not cause problems in other places

**Comment by 3buchet** [comment]
Hi @ArtCraft ,
thanks a lot for your tips. 

I am not sure I am familiar with the "arrow link" ui element. Could you please show its location on a screenshot?

FYI: what I did is just normalising colours and font sizes for top element ("Signature", if I am right) and bottom reply button. Now both should be sized to 13px and having the same "--fgSoftest" color.
Everything except the comment body got less contrast, this should improve readability of the threads as previously reader was interrupted by the username in the Signature component as it was almost the same contrast as the comment itself.

It's a bit difficult for me to find different places where those components are used, but for the "Signature" components on posts listings (on main page, search results and user profile) looks fine.
However, I would appreciate if someone who knows the project could validate and confirm.
Kind regards.

**Comment by ArtCraft** [comment]
i mean this line for comments
image

and this line for posts
image

right now font there is 14px
image


to find all usages
if you use any ide from jetbrains 
select a component name and press `ctrl` + `shift` + F (find in files)

**Comment by 3buchet** [comment]
@ArtCraft
Thank you, it's expected to appear in 13px and --fgSoftest font color for the whole Signature component: 
author username, date, "changed" and reply arrow & username:
Screenshot 2023-03-30 at 23 49 16
Screenshot 2023-03-30 at 23 48 49
Kind regards

**Review by ArtCraft — APPROVED** [review]

**Pull request merged**
