### PR TITLE
stop other videos

### PR DESCRIPTION
**Pull request by maximt**
Only one video at a time is allowed to play, other videos will be paused. 
Works with video and YouTube.
YouTube Iframe API is used for playback events.

Edit:

Added IntersectionObserver wrapper to track element's visibility and stop invisible videos that are scrolled out of the viewport.

### CODE REVIEW

**Comment by Aivean** [comment]
Sorry, didn't get the chance to review this (yet). Will do this week.

**Review by pazoozoo42 — DISMISSED** [review]
This is a great improvement, thank you! Tested locally and it works as expected

**Comment by Aivean** [comment]
One thing I'm thinking of is reverting the videos to "lightweight embed" form instead of stopping (for the videos that have this available, e.g. all youtube videos and some mp4) to save the RAM.

**Comment by maximt** [comment]
> One thing I'm thinking of is reverting the videos to "lightweight embed" form instead of stopping (for the videos that have this available, e.g. all youtube videos and some mp4) to save the RAM.

Actually, videos are paused but not stopped, and you can resume playback from the last position, I think its the most expected behavior.

**Review by Aivean — APPROVED** [review]

**Pull request merged**
