### PR TITLE
Option to edit site info for site owners

### PR DESCRIPTION
**Pull request by pazoozoo42**
rejected

### CODE REVIEW

**Comment by Aivean** [comment]
wdym "rejected"?

**Comment by pazoozoo42** [comment]
> wdym "rejected"?

Following our discussion on Discord, I’ve realized that the proposed solution may not align with the vision of most of the other developers. As a result, I’ve decided not to invest time and effort in exploring alternative solutions

**Comment by Aivean** [comment]
> > wdym "rejected"?
> 
> Following our discussion on Discord, I’ve realized that the proposed solution may not align with the vision of most of the other developers. As a result, I’ve decided not to invest time and effort in exploring alternative solutions

I proposed a relatively minor change that brings it back into alignment: instead of creating a single "owner" of the subsite, give the edit ability to the top N current contributors to the subsite content. Do you see any problems with this suggestion? Do you want me (or somebody else) try to implement it?

**Comment by pazoozoo42** [comment]
I’m personally not a big fan of the idea of having more than one owner and 'dynamic' ownership in general. This approach could lead to unpredictable consequences, edit wars similar to Barmalini posts and may potentially result in even more sraches than we already experience, and we already have quite a few

**Comment by Aivean** [comment]
> edit wars similar to Barmalini posts and may potentially result in even more sraches than we already experience, and we already have quite a few

sounds beneficial, no?

**Pull request closed without merging**
